# Generated by Django 5.2.17 on 2026-08-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[("personal", "Personal"), ("company", "Company")],
                default="personal",
                max_length=10,
            ),
        ),
    ]
