# Generated by Django 5.2.17 on 2026-08-15 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_messages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminconversation",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this is a direct 1:1 (an admin messaging a specific org owner, or a super_admin messaging a specific admin) rather than an open ticket any super_admin may pick up.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_conversations_targeted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
