# Generated by Django 5.2.17 on 2026-08-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="application_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="context_description",
            field=models.TextField(
                blank=True,
                help_text="Plain-language description of what the administration should manage — becomes context for schema analysis and AI setup.",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="environment",
            field=models.CharField(
                choices=[
                    ("development", "Development"),
                    ("staging", "Staging"),
                    ("production", "Production"),
                ],
                default="development",
                max_length=20,
            ),
        ),
    ]
