# Generated by Django 5.2.17 on 2026-08-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_application_application_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="admin_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Admin Builder config: per selected table, which columns are filters, which are form fields, and any chart definitions. Keyed by table id.",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
