# Generated by Django 5.2.17 on 2026-09-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0003_application_admin_config_application_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Set once the customer has confirmed their style/table/method choices on the review screen and published the panel.",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="panel_style",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Visual style of the generated admin panel: primary/background colors, logo URL, button style, input style, default chart type.",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="admin_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Admin Builder config: per selected table, which columns are filters, which are form fields, allowed CRUD methods, and any chart definitions. Keyed by table id.",
            ),
        ),
    ]
