# Generated by Django 5.2.17 on 2026-08-14 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseColumn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("data_type", models.CharField(max_length=100)),
                ("is_nullable", models.BooleanField(default=True)),
                ("is_primary_key", models.BooleanField(default=False)),
                ("ordinal_position", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["ordinal_position"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="public", max_length=150)),
                ("discovered_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to="connections.databaseconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="schemas.databaseschema",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("constraint_name", models.CharField(blank=True, max_length=255)),
                (
                    "from_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="schemas.databasecolumn",
                    ),
                ),
                (
                    "to_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="schemas.databasecolumn",
                    ),
                ),
                (
                    "from_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="schemas.databasetable",
                    ),
                ),
                (
                    "to_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="schemas.databasetable",
                    ),
                ),
            ],
            options={
                "ordering": ["constraint_name"],
            },
        ),
        migrations.AddField(
            model_name="databasecolumn",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="schemas.databasetable",
            ),
        ),
        migrations.AddConstraint(
            model_name="databaseschema",
            constraint=models.UniqueConstraint(
                fields=("connection", "name"), name="unique_schema_per_connection"
            ),
        ),
        migrations.AddConstraint(
            model_name="databasetable",
            constraint=models.UniqueConstraint(
                fields=("schema", "name"), name="unique_table_per_schema"
            ),
        ),
        migrations.AddConstraint(
            model_name="databasecolumn",
            constraint=models.UniqueConstraint(
                fields=("table", "name"), name="unique_column_per_table"
            ),
        ),
    ]
