# Generated by Django 5.2.17 on 2026-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasecolumn",
            name="is_allowed",
            field=models.BooleanField(
                default=True,
                help_text="Column-level permission (spec section 17) — whether this column is exposed at all within its table's allowed data access.",
            ),
        ),
        migrations.AddField(
            model_name="databasetable",
            name="is_selected",
            field=models.BooleanField(
                default=True,
                help_text="Whether this table is part of the project's allowed data-access whitelist (spec section 16) — set by the recommendation heuristic on discovery, adjustable by the customer.",
            ),
        ),
    ]
