# Generated by Django 5.2.17 on 2026-08-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_organizationmessage_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
